dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
language: csharp
mono: none

script:
  - cd ..; git clone https://github.com/Kansattica/Fluency; cd FluencyOnline
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet publish --configuration Release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $push_token
  local_dir: bin/Release/netstandard2.0/publish/FluencyOnline/dist/
  repo: Kansattica/FluencyOnline
  target-branch: gh-pages
  verbose: true
  on:
    branch: master