os: linux
dotnet: 3.1.101
language: csharp
mono: none

script:
  - cd ..; git clone https://github.com/Kansattica/Fluency; cd FluencyOnline
  - dotnet publish --configuration Release

deploy:
  provider: pages
  cleanup: false
  skip_cleanup: true
  github_token: $push_token
  local_dir: bin/Release/netstandard2.1/publish/FluencyOnline/dist/
  repo: Kansattica/FluencyOnline
  target_branch: gh-pages
  verbose: true
  on:
    branch: master